#POBRÍAMOS HACER UNA LISTA CON Fi DE TODAS LAS LETRAS DEL TEXTO, TOTAL LO VAMOS A NECESITAR USAR POSIBLEMENTE UNAS 30*27 VECES.

# TENER EN CUENTA QUE PASA SI EL LARGO DEL TEXTO (DSP DE SACARLE CARACTERES ESPECIALES) ES 0
