# QUEDAR AL TANTO DE CÓMO QUEDA LA LÍNEA DE IoC / Friedman Graph

# NO HACER LISTA CON LETRAS (LO QUE DICE ABAJO)

# FOR I IN RANGE(97,123) PARA CUANDO NECESITO TODAS LAS LETRAS

# TENER CUIDADO SI NO SE PUEDE HACER

# TENER EN CUENTA CASOS EN LOS QUE EL LARGO DEL TEXTO SEA MENOR DE 30 (con Y/N)

# SOMOS CRACKS PANAAAAAAAAAAAAAAAAAAAAAAAA

# preguntarle a guille si está bien que printee así el Friedman graph
# SOMOS CRACKS PANAAAAAAAAAAAAAAAAAAAAAAAA 🥺👉🏻👈🏻

# GRAFICO PARA GUILLE SEGÚN EL LARGO DE LA CLAVE
# HACER QUE SI EL ARCHIVO YA EXISTE, PREGUNTE SI QUIERE SOBREESCRIBIRLO