# PONER ARCHIVOS CON BARRA BAJA AL PRINCIPIO 
# QUEDAR AL TANTO DE CÓMO QUEDA LA LÍNEA DE IoC / Friedman Graph
# GRAFICO PARA GUILLE SEGÚN EL LARGO DE LA CLAVE

# TENER EN CUENTA CASOS EN LOS QUE EL LARGO DEL TEXTO SEA MENOR DE 30 (con Y/N)

# NO NOS FIJAMOS SI EL ARCHIVO EN EL QUE DESEA ESCRIBIR YA EXISTE

# EL PUNTO QUE TIENE LA AMYOR DIFERENCIA CON TODOS SUS ANTERIORES
# EL PUNTO DEL FRIEDMAN GRAPH ES EL SALTO MÁS GRANDE QUE HAYA ENTRE EL ANTERIOR MÁXIMO Y EL ACTUAL, AUNQUE RECORRAMOS TODA LA LISTA, EL SALTO CON LOS MÚLTIPLOS VA A SER CHIQUITO.
# SI EL TEXTO ES MUY LARGO NO ANDA BIEN...
# SI PONEMOS UNA CLAVE DE 30, LE ERRA EN 3 CARACTERES...
